# -*- coding: utf-8 -*-
"""while10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jLt3nfrutgqIAjVji4Cxgkigo-U3Z5uZ
"""

import time 
var = 0 
while var <= 5:
    print(var)
    time.sleep(2)
    var = var + 1

from time import sleep 
itens = ['maria','ana','matheus','paulo','bia']
for item in itens:
    print(item)
    sleep(2)

sala = []
while len(sala) <= 5:
    nome = str(input('nome do aluno: '))
    sala.append(nome)
print(sala)

sala = []
while len(sala)<=5:
    nome = str(input('nome do aluno: '))
    sala.append(nome)
for aluno in sala:
    print(sala)

nomes=[]
idades=[]
alturas=[]

cadastro=int(input('quantas pessoas moram na casa? '))
c=1
i=0
while c<= cadastro:
    nome = str(input('informe o nome: '))
    idade = int(input(f'informe a idade de {nome}: '))
    altura = float(input(f'informe a altura de {nome}: '))
    nomes.append(nome)
    idades.append(idade)
    alturas.append(altura)
    c+=1
while i <= cadastro-1:
    print(f'nome {nomes[i]} , idade {idades[i]} , altura {alturas[i]} ')
    i+=1

a=('cachorro',2,1,4,True, ['item1','item2'])
type(a)

